// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
import CitationsController from "./citations_controller"
import SourcePickerController from "./source_picker_controller"

window.Stimulus = Application.start()
Stimulus.register("citations", CitationsController)
Stimulus.register("source-picker", SourcePickerController)


const application = Application.start()
// Load your controllers
application.register("citations", CitationsController)

// Optional: export if you need to access Application elsewhere
export { application }

//  import { Application } from "@hotwired/stimulus"
//   const application = Application.start()

//   import CitationsController from "./citations_controller"
//   application.register("citations", CitationsController)



// import { Application } from "@hotwired/stimulus"
// import CitationsController from "./citations_controller"

// window.Stimulus = Application.start()
// Stimulus.register("citations", CitationsController)