// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with

// app/javascript/controllers/index.js
import { Application } from "@hotwired/stimulus"
const application = Application.start()
export { application }

// (keep your registrations)
import CitationsController from "./citations_controller"
application.register("citations", CitationsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvolvementFormController from "./involvement_form_controller"
application.register("involvement-form", InvolvementFormController)


import InvolvementPickerController from "./involvement_picker_controller"
application.register("involvement-picker", InvolvementPickerController)

import InvolvementsController from "./involvements_controller"
application.register("involvements", InvolvementsController)

import SourcePickerController from "./source_picker_controller"
application.register("source-picker", SourcePickerController)

import BurialFormController from 
"./burial_form_controller"
application.register("burial-form", 
BurialFormController)

import BurialController from 
"./burial_controller"
application.register("burial-form", 
BurialController)

