// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CitationsController from "./citations_controller"
application.register("citations", CitationsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvolvementFormController from "./involvement_form_controller"
application.register("involvement-form", InvolvementFormController)

import InvolvementsController from "./involvements_controller"
application.register("involvements", InvolvementsController)

import SourcePickerController from "./source_picker_controller"
application.register("source-picker", SourcePickerController)
