default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", `whoami`.strip) %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: jefajefa_development

test:
  <<: *default
  database: jefajefa_test

production:
  <<: *default
  database: jefajefa_production
